### PR TITLE
Adding a new website parser

### PR DESCRIPTION
**Pull request by andrewramsay**
## Summary

There are two parts to this:

1. `offline/new_parsers.md`: this doc is intended to answer the question "how do I add a new website parser to the offline pipeline?"
2. `offline/document_parsers/allrecipes_parser.py`: an example of a new parser for [allrecipes.com](https://www.allrecipes.com)

I've also modified the offline pipeline configuration a little. I had some trouble getting useful results from CommonCrawl initially so I've added a second instance of the `Scraper` component at the start of the pipeline (the first instance is used to scrape the URLs generated by the category corpus construction step). This allows it to be used instead of/as well as the `CommonCrawl` component. 

The `Scraper` now also supports adding custom HTTP headers to its requests, it turned out allrecipes.com blocks minimal HTTP GET requests so extra headers are required. 

## Testing

Try adding a few URLs to `shared/file_system/offline/non_cc_urls.csv` and run the pipeline. I just used a small test set:

```
https://www.allrecipes.com/recipe/268180/feta-roast-chicken/
https://www.allrecipes.com/recipe/242362/butterflied-roast-chicken-with-lemon-and-rosemary/
https://www.allrecipes.com/recipe/233953/million-dollar-chicken/
https://www.allrecipes.com/recipe/107488/caribbean-spiced-roast-chicken/
https://www.allrecipes.com/recipe/265562/whole-chicken-pie/
```

The log for the `Scraper` component should show something like: 

```
[2024-03-15 14:30:01,050] - INFO - local.offline - url_downloaders.py.download:137 - Scraper starting to run on 5 URLs
[2024-03-15 14:30:02,632] - INFO - local.offline - url_downloaders.py.write_protobuf_list_to_file:33 - Writing 5 protos to /shared/file_system/offline/protos/htmls/allrecipes_scraped/html_0.bin
[2024-03-15 14:30:02,679] - INFO - local.offline - url_downloaders.py.download:183 - Scraper saved HTMLs at /shared/file_system/offline/protos/htmls/allrecipes_scraped/html_0.bin
[2024-03-15 14:30:02,679] - INFO - local.offline - url_downloaders.py.download:185 - Scraper processed 5 URLs, 0 failures
[2024-03-15 14:30:02,680] - INFO - local.offline - url_downloaders.py.store_failed_urls:85 - Writing failed URLs to /shared/file_system/offline/pipeline_stats/Scraper
```

There will probably be issues with the augmenters step later in the pipeline, this should be fixed after #7 is merged.

### CODE REVIEW

**Comment by SophieFischer** [comment]
this worked but I do get errors later down the line:
`offline  | [2024-03-19 17:27:59,184] - INFO - local.offline - downloads.py.get_artefact_path:417 - Downloader(offline): found artefact domain_classifier in source domain_classifier with path /shared/file_system/downloads/offline/domain_classifier
offline  | Traceback (most recent call last):
offline  |   File "/source/main.py", line 66, in <module>
offline  |     component.run()
offline  |   File "/source/category_index/run_building_taxonomy.py", line 17, in run
offline  |     parser_runner = KnowledgeConstruction(self.html_proto_path, self.knowledge_proto_path,
offline  |   File "/source/index_builders/general_knowledge_construction.py", line 19, in __init__
offline  |     self.domain_classifier = DomainClassifier()
offline  |   File "/source/category_index/domain_classifier_categories.py", line 15, in __init__
offline  |     self.classifier.load(downloader.get_artefact_path(artefact_id))
offline  |   File "/shared/models/domain_classification/naive_bayes.py", line 191, in load
offline  |     with open(os.path.join(path, "tfidf.pkl"), "rb") as file:
offline  | FileNotFoundError: [Errno 2] No such file or directory: '/shared/file_system/downloads/offline/domain_classifier/tfidf.pkl'
offline exited with code 1`

**Comment by andrewramsay** [comment]
Something up with the S3 bucket? It looks like it's failed to download a file, and if I try the URL manually it's giving a 403:

```
$ wget https://oat-2-data-backup.s3.amazonaws.com/classifiers/domain_classifier/tfidf.pkl
--2024-03-19 17:34:11--  https://oat-2-data-backup.s3.amazonaws.com/classifiers/domain_classifier/tfidf.pkl
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving oat-2-data-backup.s3.amazonaws.com (oat-2-data-backup.s3.amazonaws.com)... 52.217.68.156, 52.216.179.211, 3.5.7.144, ...
Connecting to oat-2-data-backup.s3.amazonaws.com (oat-2-data-backup.s3.amazonaws.com)|52.217.68.156|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-03-19 17:34:11 ERROR 403: Forbidden.
```

**Comment by SophieFischer** [comment]
after running PR #9 , the same domain classifier error appears (from two comments ago https://github.com/grill-lab/OAT/pull/8#issuecomment-2007757141) - the model exists, but doesn't live in `/offline/` where the path is checking for it. This should be updates in `downloads.toml` I think!

**Comment by SophieFischer** [comment]
now it works! I think it was because main wasn't merged in. Will approve, thanks!

**Review by SophieFischer — APPROVED** [review]

**Pull request merged**
